"""
AI AGENT — LangGraph tool-calling agent.

    Question
       -> LangGraph ReAct agent plans
       -> tool call
       -> deterministic result
       -> LLM
       -> more tools if evidence is incomplete
       -> grounded structured answer

Division of labour
------------------
The LLM plans, selects tools, interprets evidence and writes the narrative.
Every number in the answer comes from a deterministic tool: amounts, threshold
comparisons, counts, 24-hour aggregation and jurisdiction lookups are computed
in ``tools/`` and handed to the model as evidence.

The tool schemas the model sees are generated by LangChain from each
function's signature and docstring (the ``@tool`` decorator in ``tools/*``) —
none are hand-written here.  The agent loop and the final structured-output
call are both built by ``langgraph.prebuilt.create_react_agent``; this module
only supplies the system prompt, the tool list, and the grounding pass applied
after the model responds:

* ``facts`` is rebuilt from the deterministic tool results, never from model
  output;
* ``citations`` are intersected with the policy documents retrieval actually
  returned, so a hallucinated or decoy filename cannot reach the submission;
* ``tools_used`` is read off the executed graph's own message trace.
"""

import json
import os
import re
import time
from collections import defaultdict

import anthropic
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, ToolMessage
from langchain_core.rate_limiters import InMemoryRateLimiter
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field

from tools.client_tools import get_client_profile
from tools.payment_tools import (
    aggregate_beneficiary_24h,
    find_repeated_beneficiaries,
    get_client_payments,
    get_payment,
)
from tools.policy_tools import search_policy
from tools.threshold_tools import evaluate_payment_thresholds, evaluate_structuring


TOOLS = [
    get_client_profile,
    get_payment,
    get_client_payments,
    aggregate_beneficiary_24h,
    find_repeated_beneficiaries,
    evaluate_payment_thresholds,
    evaluate_structuring,
    search_policy,
]


SYSTEM_PROMPT = """
You are a bank payment-investigation assistant.

Rules:
1. Retrieve transaction facts before making factual claims.
2. Use deterministic tools for arithmetic and aggregation.
3. Retrieve applicable policy evidence through RAG.
4. Separate observed facts from assumptions.
5. A policy trigger does not automatically establish suspicious activity.
6. Explain missing evidence when necessary.
7. Cite relevant policy sources.

Investigation method
--------------------
The payment record, the client profile and the deterministic threshold
evaluation for the payment under investigation are supplied to you up front.
Decide what else you need and call the tools for it:

- `search_policy` — ALWAYS call this at least once. Every policy claim you
  make must come from retrieved text. Issue separate targeted queries for
  separate topics (thresholds, high-risk destinations, structuring,
  investigation workflow) instead of one broad query.
- `get_client_payments` / `find_repeated_beneficiaries` /
  `aggregate_beneficiary_24h` / `evaluate_structuring` — for any question
  about transaction splitting, patterns, or a client's history.
- `get_client_profile` / `get_payment` — for other clients or payments.

Never compute an amount, total or threshold comparison yourself; take it from
a tool result.

Domain rules
------------
- `beneficiary_country_code` is authoritative for jurisdiction risk. The
  `beneficiary_country` name field may disagree with it; when it does, say so.
- The global policy always applies. Singapore and Switzerland clients also get
  their regional procedure, which adds requirements on top of the global one.
  Clients elsewhere are governed by the global policy alone.
- No exchange-rate data exists. When a comparison crosses currencies, state
  the 1:1 equivalence assumption in your answer.
- Multiple same-day payments above a threshold are an observed pattern that
  requires review. Intent to evade is an assumption, never an observed fact.

Answer format
-------------
Once you have enough evidence, produce the final structured answer: a compact
prose briefing under 250 words covering, in this order and only where
relevant:

1. Observed facts — payment amount, currency, destination code, client region.
2. Policy triggers — which thresholds are met or not met, and which are not.
3. Assumptions — including any currency assumption.
4. Missing evidence — what is not in the data and would be needed.
5. Recommended action — the concrete next step, including whether the payment
   requires standard, RM, enhanced, or additional review, or may proceed.

Also list the citations: only the policy documents whose rules you actually
applied, never every document you retrieved.

State clearly when no threshold is triggered and the payment needs no
enhanced review; do not manufacture concern that the evidence does not
support.
"""


class InvestigationAnswer(BaseModel):
    """Final grounded answer for one investigation question."""

    answer: str = Field(
        description=(
            "The grounded investigation briefing: observed facts, policy "
            "triggers, assumptions, missing evidence and the recommended "
            "action. Under 250 words."
        )
    )
    citations: list[str] = Field(
        default_factory=list,
        description=(
            "Policy source filenames whose rules were actually applied, "
            "exactly as returned by search_policy (e.g. "
            "'global_payment_policy.md'). Must not be empty."
        ),
    )


MAX_ITERATIONS = 12
MAX_RETRIES = 5


# HTTP statuses worth retrying: rate limit, and transient server-side failure.
_RETRYABLE_STATUS_CODES = {429, 500, 502, 503, 529}


def _with_retry(call, *args, **kwargs):
    """Retry an Anthropic call with exponential backoff on transient errors.

    Rate limits and transient overload/service-unavailable responses are
    expected under back-to-back questions; anything else (bad request, auth,
    a 4xx that isn't a rate limit) is not retried and propagates immediately.
    """
    delay = 1.0
    for attempt in range(MAX_RETRIES):
        try:
            return call(*args, **kwargs)
        except anthropic.APIConnectionError:
            if attempt == MAX_RETRIES - 1:
                raise
        except anthropic.APIStatusError as error:
            if (
                attempt == MAX_RETRIES - 1
                or error.status_code not in _RETRYABLE_STATUS_CODES
            ):
                raise
        time.sleep(delay)
        delay *= 2


def _load_env() -> None:
    """Load key=value pairs from a local .env file into the environment."""
    path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"
    )
    if not os.path.isfile(path):
        return

    with open(path, "r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip("\"'"))


def _establish_baseline(payment_id: str) -> tuple[str, list[dict]]:
    """Run the always-applicable first investigation steps deterministically.

    Steps 1-2 of the investigation procedure — establish the payment and
    client facts, identify the applicable policy — apply to every question, so
    they are executed up front and seeded into the model's context rather than
    costing a round trip.  Each call is recorded exactly like an agent tool
    call so it counts toward ``tools_used`` and the grounding pass.
    """
    records: list[dict] = []

    payment = get_payment.invoke({"payment_id": payment_id})
    records.append({"name": "get_payment", "output": payment})
    evidence = {"payment": payment}

    if isinstance(payment, dict) and "error" not in payment:
        client = get_client_profile.invoke({"client_id": payment["client_id"]})
        records.append({"name": "get_client_profile", "output": client})
        evidence["client"] = client

        threshold_evaluation = evaluate_payment_thresholds.invoke(
            {"payment_id": payment_id}
        )
        records.append(
            {"name": "evaluate_payment_thresholds", "output": threshold_evaluation}
        )
        evidence["threshold_evaluation"] = threshold_evaluation

    return json.dumps(evidence, default=str)[:12000], records


def _tool_call_records(messages) -> list[dict]:
    """Extract every executed tool call (name, output) from the agent's trace.

    LangGraph's tool node JSON-serialises any non-string tool return before
    storing it as ``ToolMessage.content`` (``_stringify`` in
    ``langchain_core.tools.base``), so a dict/list result comes back as a JSON
    string here and must be parsed back before the grounding checks below can
    inspect its shape.
    """
    records = []
    for message in messages:
        if not isinstance(message, ToolMessage):
            continue

        content = message.content
        if isinstance(content, str):
            try:
                content = json.loads(content)
            except (json.JSONDecodeError, ValueError):
                pass

        records.append({"name": message.name, "output": content})
    return records


def _target_payment_context(
    records: list[dict], payment_id: str
) -> tuple[str | None, str | None]:
    """Find the client and beneficiary of the payment under investigation.

    Used to scope structuring evidence to this payment: the system prompt
    allows the model to look up other clients/payments for comparison, and
    without this filter a structuring result for an unrelated client could be
    picked up as if it belonged to the investigated payment.
    """
    for record in records:
        output = record["output"]
        if (
            record["name"] == "get_payment"
            and isinstance(output, dict)
            and output.get("payment_id") == payment_id
            and "error" not in output
        ):
            return output.get("client_id"), output.get("beneficiary_name")
    return None, None


def _matches_target(output: dict, client_id: str | None, beneficiary_name: str | None) -> bool:
    """True when a structuring/aggregate result belongs to the target payment."""
    if client_id is None or beneficiary_name is None:
        return True  # no target context available; don't over-filter

    return output.get("client_id") == client_id and str(
        output.get("beneficiary_name", "")
    ).strip().lower() == beneficiary_name.strip().lower()


def _build_facts(records: list[dict], payment_id: str) -> dict:
    """Assemble the ``facts`` block from deterministic tool output only."""
    facts: dict = {}
    target_client_id, target_beneficiary = _target_payment_context(records, payment_id)

    threshold = next(
        (
            record["output"]
            for record in records
            if record["name"] == "evaluate_payment_thresholds"
            and isinstance(record["output"], dict)
            and "error" not in record["output"]
            and record["output"].get("payment_id") == payment_id
        ),
        None,
    )

    if threshold:
        facts.update(
            {
                "payment_id": threshold["payment_id"],
                "client_id": threshold["client_id"],
                "client_country": threshold["client_country"],
                "amount": threshold["amount"],
                "currency": threshold["currency"],
                "beneficiary_country_code": threshold["beneficiary_country_code"],
                "beneficiary_country_name": threshold["beneficiary_country_name"],
                "is_high_risk_destination": threshold["is_high_risk_destination"],
                "applicable_regional_policy": threshold["applicable_regional_policy"],
                "threshold_checks": threshold["threshold_checks"],
                "enhanced_review_required": threshold["enhanced_review_required"],
                "rm_review_required": threshold["rm_review_required"],
                "additional_review_required": threshold["additional_review_required"],
                "policy_triggers": threshold["policy_triggers"],
                "currency_assumption": threshold["currency_assumption"],
            }
        )

    structuring = next(
        (
            record["output"]
            for record in records
            if record["name"] == "evaluate_structuring"
            and isinstance(record["output"], dict)
            and "error" not in record["output"]
            and _matches_target(record["output"], target_client_id, target_beneficiary)
        ),
        None,
    )

    if structuring:
        facts["structuring_analysis"] = {
            key: structuring[key]
            for key in (
                "beneficiary_name",
                "window_date",
                "window_assumption",
                "payment_count_in_window",
                "payment_ids_in_window",
                "combined_amount",
                "combined_currency",
                "threshold_comparison",
                "structuring_review_triggered",
                "escalation_to_compliance_required",
            )
        }
    else:
        aggregate = next(
            (
                record["output"]
                for record in records
                if record["name"] == "aggregate_beneficiary_24h"
                and isinstance(record["output"], dict)
                and record["output"].get("count", 0) > 1
            ),
            None,
        )
        if aggregate:
            facts["structuring_analysis"] = {
                "beneficiary_name": aggregate["beneficiary_name"],
                "window_date": aggregate["window_date"],
                "payment_count_in_window": aggregate["count"],
                "payment_ids_in_window": [
                    payment["payment_id"] for payment in aggregate["payments"]
                ],
                "combined_amount": aggregate["total_amount"],
                "combined_currency": aggregate["currency"],
            }

    return facts


def _clean_answer(text: str) -> str:
    """Normalise the model's answer text.

    The model occasionally spills fragments of its own structured-output or
    tool-call syntax into the end of the answer string (seen in production:
    trailing ``</answer>``, ``<parameter name="citations">...`` fragments).
    Anything from such a fragment onward is not part of the briefing and is
    discarded.
    """
    if not text:
        return ""

    for marker in (
        "</answer>",
        "<parameter",
        "</invoke>",
        "<invoke",
        "</function",
        "<citations>",
        "</citations>",
    ):
        text = text.split(marker, 1)[0]

    return re.sub(r"\s+", " ", text).strip()


def _allowed_sources(records: list[dict]) -> set[str]:
    """Policy documents the run actually retrieved or relied on."""
    allowed: set[str] = set()

    for record in records:
        output = record["output"]

        if record["name"] == "search_policy" and isinstance(output, list):
            allowed.update(item["source"] for item in output)
        elif isinstance(output, dict):
            allowed.update(output.get("supporting_sources", []))

    return allowed


# A retrieved chunk below this cosine score is a weak lexical match rather
# than evidence worth citing.
_CITATION_SCORE_FLOOR = 0.20


def _derive_citations(records: list[dict]) -> list[str]:
    """Derive citations deterministically when the model supplies none.

    Prefers the documents whose rules the deterministic evaluators actually
    applied, then adds the best-scoring document from each policy search.
    """
    citations: list[str] = []

    for record in records:
        output = record["output"]
        if record["name"] in ("evaluate_payment_thresholds", "evaluate_structuring"):
            if isinstance(output, dict):
                citations.extend(output.get("supporting_sources", []))

    for record in records:
        if record["name"] != "search_policy":
            continue
        output = record["output"]
        if isinstance(output, list) and output:
            best = output[0]
            if best["score"] >= _CITATION_SCORE_FLOOR:
                citations.append(best["source"])

    return list(dict.fromkeys(citations))


def _fallback_answer(facts: dict) -> str:
    """Deterministic answer used when the LLM call cannot be completed."""
    if not facts:
        return (
            "The assistant could not complete the LLM synthesis step and no "
            "deterministic evidence was retrieved for this question."
        )

    triggers = facts.get("policy_triggers") or []
    return (
        f"Observed facts: payment {facts.get('payment_id')} of "
        f"{facts.get('amount')} {facts.get('currency')} from client "
        f"{facts.get('client_id')} ({facts.get('client_country')}) to "
        f"beneficiary country code {facts.get('beneficiary_country_code')}. "
        f"Policy triggers: {'; '.join(triggers) if triggers else 'none'}. "
        "This answer was produced from deterministic tool output only, because "
        "the LLM synthesis step failed; the narrative interpretation of the "
        "evidence is missing."
    )


_agent = None
_structured_model = None


def _get_agent(model_name: str):
    """Build the LangGraph ReAct agent once and reuse it across questions.

    The structured final answer is requested in a separate call after the
    ReAct loop finishes (see ``run_agent``) rather than through
    ``create_react_agent``'s built-in ``response_format`` node: that node
    replays the full message history — which ends on the agent's own
    assistant turn — into a forced-tool-choice call, and current Claude
    models reject a request whose transcript already ends in an assistant
    message ("prefill"). Asking separately, with a trailing human turn,
    avoids that.
    """
    global _agent, _structured_model
    if _agent is None:
        rate_limiter = InMemoryRateLimiter(
            requests_per_second=0.5,
            check_every_n_seconds=0.1,
            max_bucket_size=1,
        )
        model = ChatAnthropic(
            model=model_name, max_tokens=2000, rate_limiter=rate_limiter
        )
        _agent = create_react_agent(model, TOOLS, prompt=SYSTEM_PROMPT)
        _structured_model = model.with_structured_output(InvestigationAnswer)
    return _agent, _structured_model


def run_agent(
    question: str,
    payment_id: str,
) -> dict:
    """Answer one investigation question with a LangGraph tool-calling agent.

    Returns ``{"answer", "citations", "facts", "tools_used"}``.  The function
    never raises: on any failure it degrades to a deterministic answer built
    from whatever tool evidence was collected, so a single bad question cannot
    abort the run.
    """
    _load_env()

    baseline_json, records = _establish_baseline(payment_id)

    answer = ""
    citations: list[str] = []

    try:
        model_name = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-5")
        agent, structured_model = _get_agent(model_name)

        result = _with_retry(
            agent.invoke,
            {
                "messages": [
                    HumanMessage(
                        content=(
                            f"Investigation question: {question}\n"
                            f"Payment under investigation: {payment_id}\n\n"
                            f"Evidence already gathered (deterministic tools):\n"
                            f"{baseline_json}\n\n"
                            "Retrieve the policy evidence you need and run "
                            "any further analysis the question requires."
                        )
                    )
                ]
            },
            config={"recursion_limit": MAX_ITERATIONS * 2},
        )

        records.extend(_tool_call_records(result["messages"]))

        structured = _with_retry(
            structured_model.invoke,
            result["messages"]
            + [
                HumanMessage(
                    content=(
                        "Based on everything gathered above, give the final "
                        "grounded answer and citations now."
                    )
                )
            ],
        )
        answer = _clean_answer(structured.answer)
        citations = list(structured.citations or [])

    except Exception as error:
        records.append({"name": "_llm", "output": {"error": str(error)}})

    facts = _build_facts(records, payment_id)

    if not answer:
        answer = _fallback_answer(facts)

    # Grounding: keep only citations backed by evidence the run retrieved.
    allowed = _allowed_sources(records)
    grounded_citations = [
        source
        for source in dict.fromkeys(citations)
        if os.path.basename(source) in allowed
    ]
    if not grounded_citations:
        grounded_citations = [
            source for source in _derive_citations(records) if source in allowed
        ]

    tool_names = {t.name for t in TOOLS}
    tools_used = list(
        dict.fromkeys(
            record["name"] for record in records if record["name"] in tool_names
        )
    )

    return {
        "answer": answer,
        "citations": grounded_citations,
        "facts": facts,
        "tools_used": tools_used,
    }
